import {
  ArrowRight,
  Check,
  ChevronsUpDown,
  Circle,
  Copy,
  Edit,
  ExternalLink,
  File,
  HelpCircle,
  Home,
  Loader2,
  Mail,
  MessageSquare,
  Moon,
  Plus,
  PlusCircle,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  Sun,
  Trash,
  User,
  Workflow,
  BookOpenCheck,
  Lightbulb,
  Scale,
  FileText,
  X,
  ListChecks,
  BookOpenText,
  Library,
  PenTool, // Added PenTool
  Landmark, // Added Landmark
  Building, // Added Building
  BookOpen, // Added BookOpen
} from 'lucide-react';

const Icons = {
  arrowRight: ArrowRight,
  check: Check,
  chevronDown: ChevronsUpDown,
  circle: Circle,
  workflow: Workflow,
  close: X,
  copy: Copy,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  help: HelpCircle,
  home: Home,
  light: Sun,
  loader: Loader2,
  mail: Mail,
  messageSquare: MessageSquare,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  spinner: Loader2,
  trash: Trash,
  user: User,
  clientAdvice: Lightbulb, 
  precedentRetrieval: Scale, 
  documentSummarizer: FileText, 
  bookOpenCheck: BookOpenCheck, 
  scale: Scale, 
  fileText: FileText, 
  listChecks: ListChecks, 
  bookOpenText: BookOpenText, 
  library: Library,
  penTool: PenTool,
  landmark: Landmark,
  building: Building,
  bookOpen: BookOpen,
};

export {Icons};
